// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDth1VpVEf4ABoLf1SqnPFLgFyFHlBDFXE',
    appId: '1:52268043572:web:cbf2b78dee4fea353aa961',
    messagingSenderId: '52268043572',
    projectId: 'pasteles-882b1',
    authDomain: "pasteles-882b1.firebaseapp.com",
    storageBucket: 'pasteles-882b1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdbunDIUcp-DfYZmnq1uW-2zvTEAYyZps',
    appId: '1:52268043572:android:9a90a977762692683aa961',
    messagingSenderId: '52268043572',
    projectId: 'pasteles-882b1',
    storageBucket: 'pasteles-882b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEkPo8ZPUqqjCENbYI8cXIJ_CIaT9C3yg',
    appId: '1:52268043572:ios:a99720bda9efaf593aa961',
    messagingSenderId: '52268043572',
    projectId: 'pasteles-882b1',
    storageBucket: 'pasteles-882b1.appspot.com',
    iosBundleId: 'com.example.pastel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEkPo8ZPUqqjCENbYI8cXIJ_CIaT9C3yg',
    appId: '1:52268043572:ios:4a81e2b1c25043dd3aa961',
    messagingSenderId: '52268043572',
    projectId: 'pasteles-882b1',
    storageBucket: 'pasteles-882b1.appspot.com',
    iosBundleId: 'com.example.pastel.RunnerTests',
  );
}
